
import { useState, useEffect, useRef } from "react"
type Prod = { name: string; price: number; img: string }
type Stall = { id: string; name: string; owner: string; x: number; y: number; color: string; emoji: string; products: Prod[]; whatsapp: string; views: number }
const STALLS: Stall[] = [
  { id:"1", name:"Aisha Fabrics", owner:"Aisha Block A12", x:1, y:1, color:"#c17c4b", emoji:"👗", whatsapp:"08031234567", views:124, products:[{name:"Ankara 6 Yards", price:15000, img:"https://picsum.photos/200/200?1"},{name:"Swiss Lace", price:45000, img:"https://picsum.photos/200/200?2"},{name:"Adire", price:12000, img:"https://picsum.photos/200/200?3"}]},
  { id:"2", name:"Chinedu Phones", owner:"Banex Shop 7", x:3.5, y:1, color:"#2b5fff", emoji:"📱", whatsapp:"08061234567", views:302, products:[{name:"iPhone 15 Pro", price:890000, img:"https://picsum.photos/200/200?4"},{name:"S24 Ultra", price:650000, img:"https://picsum.photos/200/200?5"},{name:"Powerbank", price:15000, img:"https://picsum.photos/200/200?6"}]},
  { id:"3", name:"Blessing Thrift", owner:"Block C", x:6, y:1, color:"#e3a008", emoji:"👚", whatsapp:"08031234567", views:89, products:[{name:"Okrika Grade1", price:5000, img:"https://picsum.photos/200/200?7"},{name:"Vintage Jeans", price:8000, img:"https://picsum.photos/200/200?8"},{name:"Designer Top", price:4000, img:"https://picsum.photos/200/200?9"}]},
  { id:"4", name:"Alhaji Rice", owner:"Utako", x:8.5, y:1, color:"#1a8a4a", emoji:"🍚", whatsapp:"08091234567", views:210, products:[{name:"Mama Gold 50kg", price:62000, img:"https://picsum.photos/200/200?10"},{name:"Tomato Basket", price:12000, img:"https://picsum.photos/200/200?11"},{name:"Oil 25L", price:35000, img:"https://picsum.photos/200/200?12"}]},
  { id:"5", name:"Kado Fish", owner:"Iya Kado", x:11, y:1, color:"#0e7490", emoji:"🐟", whatsapp:"08031234567", views:95, products:[{name:"Catfish 1kg", price:3500, img:"https://picsum.photos/200/200?13"},{name:"Tilapia", price:4000, img:"https://picsum.photos/200/200?14"},{name:"Smoked Fish", price:5000, img:"https://picsum.photos/200/200?15"}]},
  { id:"6", name:"Emab Gadgets", owner:"Emab Plaza", x:1, y:3.5, color:"#7c3aed", emoji:"💻", whatsapp:"08061234567", views:180, products:[{name:"HP Laptop", price:320000, img:"https://picsum.photos/200/200?16"},{name:"Mouse", price:5000, img:"https://picsum.photos/200/200?17"},{name:"Charger", price:7000, img:"https://picsum.photos/200/200?18"}]},
  { id:"7", name:"Garki Shoes", owner:"Emeka", x:3.5, y:3.5, color:"#57534e", emoji:"👟", whatsapp:"08031234567", views:67, products:[{name:"Nike Air", price:45000, img:"https://picsum.photos/200/200?19"},{name:"Palms", price:12000, img:"https://picsum.photos/200/200?20"},{name:"Loafers", price:25000, img:"https://picsum.photos/200/200?21"}]},
  { id:"8", name:"Mama Gold", owner:"Garki", x:6, y:3.5, color:"#1a8a4a", emoji:"🍲", whatsapp:"08091234567", views:143, products:[{name:"Egusi Paint", price:8000, img:"https://picsum.photos/200/200?22"},{name:"Palm Oil", price:6000, img:"https://picsum.photos/200/200?23"},{name:"Stock Fish", price:15000, img:"https://picsum.photos/200/200?24"}]},
  { id:"9", name:"Musa Building", owner:"Dei-Dei", x:8.5, y:3.5, color:"#57534e", emoji:"🧱", whatsapp:"08031234567", views:54, products:[{name:"Cement Dangote", price:9500, img:"https://picsum.photos/200/200?25"},{name:"Iron Rod", price:7000, img:"https://picsum.photos/200/200?26"},{name:"Tiles Box", price:12000, img:"https://picsum.photos/200/200?27"}]},
  { id:"10", name:"Hajia Tomatoes", owner:"Utako", x:11, y:3.5, color:"#dc2626", emoji:"🍅", whatsapp:"08091234567", views:201, products:[{name:"Tomatoes Big Basket", price:25000, img:"https://picsum.photos/200/200?28"},{name:"Pepper", price:8000, img:"https://picsum.photos/200/200?29"},{name:"Onions", price:15000, img:"https://picsum.photos/200/200?30"}]},
  { id:"11", name:"Deola Perfume", owner:"Wuse 2", x:1, y:6, color:"#ec4899", emoji:"💄", whatsapp:"08031234567", views:112, products:[{name:"Dubai Perfume", price:12000, img:"https://picsum.photos/200/200?31"},{name:"Body Spray", price:3500, img:"https://picsum.photos/200/200?32"},{name:"Cream", price:5000, img:"https://picsum.photos/200/200?33"}]},
  { id:"12", name:"Segun Watches", owner:"Banex", x:3.5, y:6, color:"#000", emoji:"⌚", whatsapp:"08061234567", views:98, products:[{name:"Rolex", price:35000, img:"https://picsum.photos/200/200?34"},{name:"G-Shock", price:25000, img:"https://picsum.photos/200/200?35"},{name:"Smart Watch", price:18000, img:"https://picsum.photos/200/200?36"}]},
  { id:"13", name:"Uche Fashion", owner:"Wuse", x:6, y:6, color:"#c17c4b", emoji:"👜", whatsapp:"08031234567", views:76, products:[{name:"Handbag Leather", price:25000, img:"https://picsum.photos/200/200?37"},{name:"Slippers", price:8000, img:"https://picsum.photos/200/200?38"},{name:"Wrist Bag", price:12000, img:"https://picsum.photos/200/200?39"}]},
  { id:"14", name:"Binta Kids", owner:"Garki", x:8.5, y:6, color:"#e3a008", emoji:"🧒", whatsapp:"08031234567", views:65, products:[{name:"Kids Cloth Set", price:7000, img:"https://picsum.photos/200/200?40"},{name:"School Bag", price:9000, img:"https://picsum.photos/200/200?41"},{name:"Shoes Kids", price:6000, img:"https://picsum.photos/200/200?42"}]},
  { id:"15", name:"James Electronics", owner:"Emab", x:11, y:6, color:"#2b5fff", emoji:"🔌", whatsapp:"08061234567", views:134, products:[{name:"TV 43\"", price:180000, img:"https://picsum.photos/200/200?43"},{name:"Speaker JBL", price:45000, img:"https://picsum.photos/200/200?44"},{name:"Extension", price:5000, img:"https://picsum.photos/200/200?45"}]},
  { id:"16", name:"Fatima Abaya", owner:"Wuse", x:1, y:8.5, color:"#000", emoji:"🧕", whatsapp:"08031234567", views:88, products:[{name:"Abaya Dubai", price:35000, img:"https://picsum.photos/200/200?46"},{name:"Jalab", price:20000, img:"https://picsum.photos/200/200?47"},{name:"Veil", price:5000, img:"https://picsum.photos/200/200?48"}]},
  { id:"17", name:"Okoro Drinks", owner:"Utako", x:3.5, y:8.5, color:"#dc2626", emoji:"🍾", whatsapp:"08091234567", views:156, products:[{name:"Coke Pack", price:6000, img:"https://picsum.photos/200/200?49"},{name:"Malt", price:7000, img:"https://picsum.photos/200/200?50"},{name:"Water Pack", price:3000, img:"https://picsum.photos/200/200?51"}]},
  { id:"18", name:"Sarah Hair", owner:"Wuse 2", x:6, y:8.5, color:"#ec4899", emoji:"💇‍♀️", whatsapp:"08031234567", views:221, products:[{name:"Bone Straight 22\"", price:65000, img:"https://picsum.photos/200/200?52"},{name:"Wig Cap", price:25000, img:"https://picsum.photos/200/200?53"},{name:"Attachment", price:4000, img:"https://picsum.photos/200/200?54"}]},
  { id:"19", name:"Danladi Meat", owner:"Kado", x:8.5, y:8.5, color:"#7f1d1d", emoji:"🥩", whatsapp:"08031234567", views:92, products:[{name:"Beef 1kg", price:5000, img:"https://picsum.photos/200/200?55"},{name:"Suya", price:2000, img:"https://picsum.photos/200/200?56"},{name:"Chicken", price:8000, img:"https://picsum.photos/200/200?57"}]},
  { id:"20", name:"Grace Tailor", owner:"Garki", x:11, y:8.5, color:"#c17c4b", emoji:"✂️", whatsapp:"08031234567", views:110, products:[{name:"Sew Native", price:8000, img:"https://picsum.photos/200/200?58"},{name:"Amend Cloth", price:2000, img:"https://picsum.photos/200/200?59"},{name:"Design", price:15000, img:"https://picsum.photos/200/200?60"}]},
]
export default function App(){
  const [player,setPlayer]=useState({x:6,y:0})
  const [near,setNear]=useState<Stall|null>(null)
  const [sel,setSel]=useState<Stall|null>(null)
  const [stalls,setStalls]=useState<Stall[]>(()=>{
    const s=localStorage.getItem("wuse_pixel_v20"); return s?JSON.parse(s):STALLS
  })
  const [page,setPage]=useState("game")
  const [pw,setPw]=useState("")
  const [isAdmin,setIsAdmin]=useState(false)
  const keys=useRef<{[k:string]:boolean}>({})
  const dots=[{x:2,y:2,c:"#ff0"},{x:5,y:4,c:"#0ff"},{x:9,y:2,c:"#f0f"},{x:2,y:7,c:"#0f0"},{x:10,y:9,c:"#fff"},{x:6,y:8,c:"#f00"},{x:1,y:5,c:"#00f"},{x:8,y:6,c:"#ffa500"}]
  useEffect(()=>{localStorage.setItem("wuse_pixel_v20",JSON.stringify(stalls))},[stalls])
  useEffect(()=>{ if(window.location.pathname.includes("super-admin")) setPage("admin") },[])
  useEffect(()=>{
    const d=(e:KeyboardEvent)=>keys.current[e.key.toLowerCase()]=true
    const u=(e:KeyboardEvent)=>keys.current[e.key.toLowerCase()]=false
    window.addEventListener("keydown",d); window.addEventListener("keyup",u)
    const id=setInterval(()=>{
      let nx=player.x, ny=player.y
      if(keys.current["w"]||keys.current["arrowup"]) ny-=0.2
      if(keys.current["s"]||keys.current["arrowdown"]) ny+=0.2
      if(keys.current["a"]||keys.current["arrowleft"]) nx-=0.2
      if(keys.current["d"]||keys.current["arrowright"]) nx+=0.2
      nx=Math.max(0,Math.min(12,nx)); ny=Math.max(0,Math.min(10,ny))
      setPlayer({x:nx,y:ny})
    },30)
    return ()=>{clearInterval(id); window.removeEventListener("keydown",d); window.removeEventListener("keyup",u)}
  },[player])
  useEffect(()=>{ setNear(stalls.find(s=>Math.abs(s.x-player.x)<1&&Math.abs(s.y-player.y)<1)||null) },[player,stalls])

  if(page==="admin"){
    if(!isAdmin) return <div className="min-h-screen bg-black text-white flex items-center justify-center p-6"><div className="bg-zinc-900 border border-zinc-800 rounded-[24px] p-8 w-full max-w-sm"><h1 className="font-black text-2xl">CEO SUPER ADMIN</h1><p className="font-mono text-[10px] text-zinc-500">20 STALLS PIXEL MAP</p><input type="password" value={pw} onChange={e=>setPw(e.target.value)} placeholder="Samuel239" className="w-full bg-black border border-zinc-800 p-4 rounded-full mt-6"/><button onClick={()=>pw==="Samuel239"?setIsAdmin(true):alert("Wrong")} className="w-full bg-white text-black p-4 rounded-full font-black mt-3">UNLOCK</button><button onClick={()=>{window.history.pushState({},'','/'); setPage('game')}} className="w-full text-zinc-500 text-xs mt-3">← Market</button></div></div>
    return <div className="min-h-screen bg-black text-white p-6"><div className="flex justify-between max-w-6xl mx-auto"><h1 className="font-black text-3xl">CEO DASHBOARD</h1><button onClick={()=>{window.history.pushState({},'','/'); setPage('game')}} className="bg-white text-black px-5 py-2 rounded-full font-bold text-sm">MARKET →</button></div><div className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-6 max-w-6xl mx-auto"><div className="bg-zinc-900 border border-zinc-800 rounded-[20px] p-5"><p className="font-mono text-[10px] text-zinc-500">TOTAL STALLS</p><p className="font-black text-3xl">20</p></div><div className="bg-zinc-900 border border-zinc-800 rounded-[20px] p-5"><p className="font-mono text-[10px] text-zinc-500">TOTAL VIEWS</p><p className="font-black text-3xl">{stalls.reduce((a,b)=>a+b.views,0)}</p></div><div className="bg-zinc-900 border border-zinc-800 rounded-[20px] p-5"><p className="font-mono text-[10px] text-zinc-500">LIVE VISITORS</p><p className="font-black text-3xl">8</p></div><div className="bg-white text-black rounded-[20px] p-5"><p className="font-mono text-[10px]">TOP STALL</p><p className="font-black text-sm">{stalls.sort((a,b)=>b.views-a.views)[0].name}</p></div></div><div className="bg-zinc-900 border border-zinc-800 rounded-[24px] p-5 mt-8 max-w-6xl mx-auto">{stalls.map(s=><div key={s.id} className="flex justify-between py-2 border-b border-zinc-800 text-sm"><span>{s.emoji} {s.name} - {s.views} views</span><button onClick={()=>setStalls(stalls.filter(x=>x.id!==s.id))} className="text-red-500 font-bold text-xs">Delete</button></div>)}</div></div>
  }

  return (
    <div className="h-[100dvh] bg-black text-white flex flex-col overflow-hidden">
      <div className="bg-zinc-900 border-b border-zinc-800 p-3 flex justify-between items-center"><h1 className="font-black tracking-tighter">WUSE MARKET ONLINE<span className="text-zinc-600">.PIXEL • 20 STALLS</span></h1><span className="text-[10px] font-mono bg-green-500/20 text-green-400 px-3 py-1 rounded-full">{near?`NEAR ${near.name.toUpperCase()}`:"WALKING..."}</span></div>
      <div className="flex-1 relative bg-[#121212] overflow-hidden">
        <div className="absolute inset-0" style={{backgroundImage:"linear-gradient(#222 1px, transparent 1px), linear-gradient(90deg, #222 1px, transparent 1px)", backgroundSize:"50px 50px"}}></div>
        <div className="absolute top-[24%] left-0 right-0 h-[14px] bg-[#2a2a2a]"></div><div className="absolute top-[49%] left-0 right-0 h-[14px] bg-[#2a2a2a]"></div><div className="absolute top-[74%] left-0 right-0 h-[14px] bg-[#2a2a2a]"></div>
        <div className="absolute left-[23%] top-0 bottom-0 w-[14px] bg-[#2a2a2a]"></div><div className="absolute left-[48%] top-0 bottom-0 w-[14px] bg-[#2a2a2a]"></div><div className="absolute left-[73%] top-0 bottom-0 w-[14px] bg-[#2a2a2a]"></div>
        {stalls.map(s=><div key={s.id} onClick={()=>{setSel(s); setStalls(p=>p.map(x=>x.id===s.id?{...x,views:x.views+1}:x))}} className="absolute cursor-pointer hover:scale-110 transition" style={{left:`${(s.x/12)*100}%`, top:`${(s.y/10)*100}%`}}><div className="w-[60px] h-[60px] md:w-[70px] md:h-[70px] rounded-[12px] border-[3px] border-black flex flex-col items-center justify-center shadow-[3px_3px_0px_black]" style={{background:s.color}}><span className="text-xl">{s.emoji}</span><span className="font-black text-[6px] text-black text-center leading-none px-1">{s.name}</span></div><div className="bg-black text-white text-[7px] text-center rounded-full mt-1 px-1">{s.views} views</div></div>)}
        {dots.map((o,i)=><div key={i} className="absolute w-3 h-3 rounded-full border-2 border-black animate-pulse" style={{left:`${(o.x/12)*100}%`, top:`${(o.y/10)*100}%`, background:o.c}}></div>)}
        <div className="absolute w-8 h-8 z-10 transition-all duration-100" style={{left:`calc(${(player.x/12)*100}% - 16px)`, top:`calc(${(player.y/10)*100}% - 16px)`}}><div className="w-8 h-8 bg-white border-[3px] border-black rounded-full flex items-center justify-center">🧑🏿‍🦱</div><div className="absolute -bottom-2 left-1/2 -translate-x-1/2 bg-black text-white text-[7px] px-2 rounded-full font-mono">YOU</div></div>
        {near&&!sel&&<div className="absolute bottom-28 left-1/2 -translate-x-1/2 bg-white text-black px-6 py-3 rounded-full font-black shadow-[4px_4px_0px_black] animate-bounce cursor-pointer text-sm" onClick={()=>{setSel(near); setStalls(p=>p.map(x=>x.id===near.id?{...x,views:x.views+1}:x))}}>PRESS TO SHOP {near.emoji} {near.name.toUpperCase()} →</div>}
        <div className="absolute bottom-5 left-5 md:hidden"><div className="w-[120px] h-[120px] bg-white/10 backdrop-blur border border-white/20 rounded-full flex items-center justify-center"><div className="grid grid-cols-3 gap-1"><div></div><button onTouchStart={()=>setPlayer(p=>({...p,y:Math.max(0,p.y-0.5)}))} className="w-10 h-10 bg-white text-black rounded-full font-black">↑</button><div></div><button onTouchStart={()=>setPlayer(p=>({...p,x:Math.max(0,p.x-0.5)}))} className="w-10 h-10 bg-white text-black rounded-full font-black">←</button><div className="w-10 h-10 bg-black rounded-full border border-zinc-700"></div><button onTouchStart={()=>setPlayer(p=>({...p,x:Math.min(12,p.x+0.5)}))} className="w-10 h-10 bg-white text-black rounded-full font-black">→</button><div></div><button onTouchStart={()=>setPlayer(p=>({...p,y:Math.min(10,p.y+0.5)}))} className="w-10 h-10 bg-white text-black rounded-full font-black">↓</button><div></div></div></div><p className="text-[9px] font-mono text-zinc-500 mt-2 text-center">JOYSTICK</p></div>
        <div className="absolute bottom-5 right-5 hidden md:block bg-zinc-900 border border-zinc-800 px-4 py-2 rounded-full font-mono text-[10px] text-zinc-400">WASD to walk • Click stall to shop</div>
      </div>
      {sel&&<div className="absolute inset-0 bg-black/80 backdrop-blur-sm z-50 flex items-end md:items-center justify-center p-0 md:p-6"><div className="bg-white text-black w-full md:max-w-lg rounded-t-[28px] md:rounded-[28px] overflow-hidden max-h-[85dvh] flex flex-col"><div className="p-5" style={{background:sel.color}}><div className="flex justify-between items-start"><div className="flex gap-3"><div className="w-14 h-14 bg-black rounded-[14px] flex items-center justify-center text-2xl">{sel.emoji}</div><div><h2 className="font-black text-lg">{sel.name.toUpperCase()}</h2><p className="font-mono text-xs">{sel.owner} • {sel.views} visits</p></div></div><button onClick={()=>setSel(null)} className="bg-black text-white w-10 h-10 rounded-full">×</button></div></div><div className="p-4 space-y-3 overflow-y-auto"><p className="font-mono text-[10px] text-zinc-500">3 PRODUCTS • PAY ON DELIVERY • ABUJA ONLY</p>{sel.products.map((pr,i)=><div key={i} className="flex gap-3 border-2 border-black rounded-[16px] p-3"><img src={pr.img} className="w-20 h-20 rounded-[12px] object-cover border-2 border-black"/><div><p className="font-bold text-sm">{pr.name}</p><p className="font-black">₦{pr.price.toLocaleString()}</p><p className="font-mono text-[10px] text-zinc-500">In stock</p></div></div>)}</div><div className="p-4 bg-zinc-50 border-t"><a href={`https://wa.me/234${sel.whatsapp.slice(1)}?text=Hi ${sel.name}, I saw you on WUSE MARKET ONLINE pixel map`} target="_blank" className="w-full bg-[#25D366] text-black p-4 rounded-full font-black block text-center shadow-[4px_4px_0px_black]">💬 CHAT ON WHATSAPP →</a><p className="font-mono text-[9px] text-center mt-2 text-zinc-500">Tracked in Firebase • Real business</p></div></div></div>}
    </div>
  )
}
